package com.model.mssql;
// Generated 23/01/2023 11:05:31 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdmArea generated by hbm2java
 */
public class AdmArea  implements java.io.Serializable {


     private int idArea;
     private String areaNombre;
     private int status;
     private Long idAplicacion;
     private Set<AdmUsuarios> admUsuarioses = new HashSet<AdmUsuarios>(0);

    public AdmArea() {
    }

	
    public AdmArea(int idArea, String areaNombre, int status) {
        this.idArea = idArea;
        this.areaNombre = areaNombre;
        this.status = status;
    }
    public AdmArea(int idArea, String areaNombre, int status, Long idAplicacion, Set<AdmUsuarios> admUsuarioses) {
       this.idArea = idArea;
       this.areaNombre = areaNombre;
       this.status = status;
       this.idAplicacion = idAplicacion;
       this.admUsuarioses = admUsuarioses;
    }
   
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }
    public String getAreaNombre() {
        return this.areaNombre;
    }
    
    public void setAreaNombre(String areaNombre) {
        this.areaNombre = areaNombre;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Long getIdAplicacion() {
        return this.idAplicacion;
    }
    
    public void setIdAplicacion(Long idAplicacion) {
        this.idAplicacion = idAplicacion;
    }
    public Set<AdmUsuarios> getAdmUsuarioses() {
        return this.admUsuarioses;
    }
    
    public void setAdmUsuarioses(Set<AdmUsuarios> admUsuarioses) {
        this.admUsuarioses = admUsuarioses;
    }




}


