package com.model.mssql;
// Generated 23/01/2023 11:05:31 AM by Hibernate Tools 4.3.1



/**
 * AdmPermisos generated by hbm2java
 */
public class AdmPermisos  implements java.io.Serializable {


     private int id;
     private Integer idPadre;
     private String modulo;
     private String link;
     private String functions;
     private Long idAplicacion;

    public AdmPermisos() {
    }

	
    public AdmPermisos(int id, String modulo) {
        this.id = id;
        this.modulo = modulo;
    }
    public AdmPermisos(int id, Integer idPadre, String modulo, String link, String functions, Long idAplicacion) {
       this.id = id;
       this.idPadre = idPadre;
       this.modulo = modulo;
       this.link = link;
       this.functions = functions;
       this.idAplicacion = idAplicacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdPadre() {
        return this.idPadre;
    }
    
    public void setIdPadre(Integer idPadre) {
        this.idPadre = idPadre;
    }
    public String getModulo() {
        return this.modulo;
    }
    
    public void setModulo(String modulo) {
        this.modulo = modulo;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getFunctions() {
        return this.functions;
    }
    
    public void setFunctions(String functions) {
        this.functions = functions;
    }
    public Long getIdAplicacion() {
        return this.idAplicacion;
    }
    
    public void setIdAplicacion(Long idAplicacion) {
        this.idAplicacion = idAplicacion;
    }




}


