package com.model.mssql;
// Generated 23/01/2023 11:05:31 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * AdmPerfil generated by hbm2java
 */
public class AdmPerfil  implements java.io.Serializable {


     private int idPerfil;
     private Serializable descripcion;
     private Serializable permisos;
     private Long idAplicacion;
     private Set<AdmUsuarios> admUsuarioses = new HashSet<AdmUsuarios>(0);

    public AdmPerfil() {
    }

	
    public AdmPerfil(int idPerfil, Serializable descripcion, Serializable permisos) {
        this.idPerfil = idPerfil;
        this.descripcion = descripcion;
        this.permisos = permisos;
    }
    public AdmPerfil(int idPerfil, Serializable descripcion, Serializable permisos, Long idAplicacion, Set<AdmUsuarios> admUsuarioses) {
       this.idPerfil = idPerfil;
       this.descripcion = descripcion;
       this.permisos = permisos;
       this.idAplicacion = idAplicacion;
       this.admUsuarioses = admUsuarioses;
    }
   
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public Serializable getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(Serializable descripcion) {
        this.descripcion = descripcion;
    }
    public Serializable getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Serializable permisos) {
        this.permisos = permisos;
    }
    public Long getIdAplicacion() {
        return this.idAplicacion;
    }
    
    public void setIdAplicacion(Long idAplicacion) {
        this.idAplicacion = idAplicacion;
    }
    public Set<AdmUsuarios> getAdmUsuarioses() {
        return this.admUsuarioses;
    }
    
    public void setAdmUsuarioses(Set<AdmUsuarios> admUsuarioses) {
        this.admUsuarioses = admUsuarioses;
    }




}


