package com.model.mssql;
// Generated 23/01/2023 11:05:31 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * AdmUsuarios generated by hbm2java
 */
public class AdmUsuarios  implements java.io.Serializable {


     private Serializable idUsuario;
     private AdmArea admArea;
     private AdmPerfil admPerfil;
     private String nombre;
     private Serializable password;
     private String email;
     private Long idAplicacion;
     private Integer idZona;
     private Serializable fechaExpiracion;
     private Boolean statusPassword;
     private Boolean jefeArea;
     private Boolean statusUsuario;
     private Boolean idAreaIngresos;
     private Boolean jefeCoordinador;

    public AdmUsuarios() {
    }

	
    public AdmUsuarios(Serializable idUsuario, AdmPerfil admPerfil, String nombre, Serializable password, String email) {
        this.idUsuario = idUsuario;
        this.admPerfil = admPerfil;
        this.nombre = nombre;
        this.password = password;
        this.email = email;
    }
    public AdmUsuarios(Serializable idUsuario, AdmArea admArea, AdmPerfil admPerfil, String nombre, Serializable password, String email, Long idAplicacion, Integer idZona, Serializable fechaExpiracion, Boolean statusPassword, Boolean jefeArea, Boolean statusUsuario, Boolean idAreaIngresos, Boolean jefeCoordinador) {
       this.idUsuario = idUsuario;
       this.admArea = admArea;
       this.admPerfil = admPerfil;
       this.nombre = nombre;
       this.password = password;
       this.email = email;
       this.idAplicacion = idAplicacion;
       this.idZona = idZona;
       this.fechaExpiracion = fechaExpiracion;
       this.statusPassword = statusPassword;
       this.jefeArea = jefeArea;
       this.statusUsuario = statusUsuario;
       this.idAreaIngresos = idAreaIngresos;
       this.jefeCoordinador = jefeCoordinador;
    }
   
    public Serializable getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Serializable idUsuario) {
        this.idUsuario = idUsuario;
    }
    public AdmArea getAdmArea() {
        return this.admArea;
    }
    
    public void setAdmArea(AdmArea admArea) {
        this.admArea = admArea;
    }
    public AdmPerfil getAdmPerfil() {
        return this.admPerfil;
    }
    
    public void setAdmPerfil(AdmPerfil admPerfil) {
        this.admPerfil = admPerfil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Serializable getPassword() {
        return this.password;
    }
    
    public void setPassword(Serializable password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Long getIdAplicacion() {
        return this.idAplicacion;
    }
    
    public void setIdAplicacion(Long idAplicacion) {
        this.idAplicacion = idAplicacion;
    }
    public Integer getIdZona() {
        return this.idZona;
    }
    
    public void setIdZona(Integer idZona) {
        this.idZona = idZona;
    }
    public Serializable getFechaExpiracion() {
        return this.fechaExpiracion;
    }
    
    public void setFechaExpiracion(Serializable fechaExpiracion) {
        this.fechaExpiracion = fechaExpiracion;
    }
    public Boolean getStatusPassword() {
        return this.statusPassword;
    }
    
    public void setStatusPassword(Boolean statusPassword) {
        this.statusPassword = statusPassword;
    }
    public Boolean getJefeArea() {
        return this.jefeArea;
    }
    
    public void setJefeArea(Boolean jefeArea) {
        this.jefeArea = jefeArea;
    }
    public Boolean getStatusUsuario() {
        return this.statusUsuario;
    }
    
    public void setStatusUsuario(Boolean statusUsuario) {
        this.statusUsuario = statusUsuario;
    }
    public Boolean getIdAreaIngresos() {
        return this.idAreaIngresos;
    }
    
    public void setIdAreaIngresos(Boolean idAreaIngresos) {
        this.idAreaIngresos = idAreaIngresos;
    }
    public Boolean getJefeCoordinador() {
        return this.jefeCoordinador;
    }
    
    public void setJefeCoordinador(Boolean jefeCoordinador) {
        this.jefeCoordinador = jefeCoordinador;
    }




}


